sudo: false
dist: trusty

language: node_js
node_js:
  - "8"

cache:
    yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
#  - yarn global add codecov

script:
  - yarn lint
  - yarn docs:build
#  - yarn test && codecov
