dist: bionic

language: node_js
node_js: 
  - lts/*
  - node

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

stages:
  - test
  - deploy

install: 
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn docs:build

jobs:
  include:
    - if: branch = master AND type = push
      stage: deploy
      name: Deploy
      node_js: node
      script: 
        - yarn semantic-release
