dist: bionic

language: node_js
node_js: 
  - lts/*
  - node

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: Testing
      
      install: 
        - yarn install --frozen-lockfile
      script:
        - yarn lint
        - yarn docs:build

    - if: branch = master AND type = push
      stage: deploy
      name: Deploy
      node_js: node
      
      install: 
        - yarn install --frozen-lockfile
      script: 
        - yarn semantic-release
