dist: bionic

language: node_js

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

install:
  - yarn install --frozen-lockfile

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: Testing
      node_js:
        - lts/*
        - node
      script:
        - yarn lint
        - yarn docs:build

    - stage: deploy
      name: Deploy
      if: branch = master AND type = push
      node_js: node
      script: yarn semantic-release
